import "%modules%/header/header";
import "%modules%/main_reds/main_reds";
import "%modules%/main_rmap/main_rmap";
import "%modules%/main_blocks/main_blocks";
import "%modules%/main_red/main_red";
import "%modules%/main_pref/main_pref";
import "%modules%/main_first/main_first";
import "%modules%/main_contacts/main_contacts";
import "%modules%/footer/footer"